export const PROJECTS = [
  {
    id: "tillflow",
    title: "TillFlow",
    description: "A comprehensive business operations management system designed for agility and precision.",
    category: "Operations",
    status: "Beta",
    metrics: [""],
    color: "from-blue-500/20 to-cyan-500/20",
  },
  {
    id: "flowcard",
    title: "FlowCard",
    description: "Next-generation digital business cards with seamless QR sharing and analytics.",
    category: "Identity",
    status: "Live",
    metrics: ["QR Sharing", "Analytics Dashboard"],
    color: "from-purple-500/20 to-pink-500/20",
  },
  {
    id: "bookflow",
    title: "BookFlow",
    description: "Intelligent booking and appointment management for service-oriented businesses.",
    category: "Scheduling",
    status: "MVP",
    metrics: ["Automation Enabled", "Multi-timezone"],
    color: "from-orange-500/20 to-red-500/20",
  },
  {
    id: "stocklite",
    title: "StockLite",
    description: "Ultra-lean inventory tracking system focusing on core essentials and speed.",
    category: "Inventory",
    status: "In Development",
    metrics: ["Real-time Sync", "Lightweight"],
    color: "from-emerald-500/20 to-teal-500/20",
  },
  {
    id: "quoteforge",
    title: "QuoteForge",
    description: "Professional invoice and quotation generator for freelancers and small agencies.",
    category: "Finance",
    status: "Beta",
    metrics: ["Template Engine", "PDF Export"],
    color: "from-indigo-500/20 to-blue-500/20",
  },
  {
    id: "shiftsync",
    title: "ShiftSync",
    description: "Modern staff attendance and shift tracking with integrated geofencing.",
    category: "HR Tech",
    status: "In Development",
    metrics: ["Geofencing API", "Clock-in/out"],
    color: "from-amber-500/20 to-yellow-500/20",
  },
];

export const SERVICES = [
  {
    title: "Business Websites",
    description: "Modern responsive websites built for brands, startups, portfolios, and businesses.",
    price: "From R3,500",
    features: [
      "Responsive Design",
      "SEO Optimization",
      "Fast Loading Speed",
      "Contact Forms",
      "Modern UI/UX",
    ],
  },
  {
    title: "Web Applications",
    description: "Custom web apps for booking systems, dashboards, admin panels, SaaS products, and automation.",
    price: "From R8,000",
    features: [
      "Authentication",
      "Dashboards",
      "Database Integration",
      "API Integration",
      "Custom Features",
    ],
  },
  {
    title: "E-Commerce Stores",
    description: "Professional online stores designed to help businesses sell products digitally.",
    price: "From R6,000",
    features: [
      "Payment Integration",
      "Product Management",
      "Shopping Cart",
      "Order Tracking",
      "Mobile Friendly",
    ],
  },
  {
    title: "Logo Design",
    description: "Minimal, modern, and memorable logos crafted for businesses and personal brands.",
    price: "From R800",
    features: [
      "High Resolution",
      "Brand Identity",
      "Multiple Concepts",
      "Transparent Files",
      "Social Media Kit",
    ],
  },
  {
    title: "Brand Identity",
    description: "Complete branding packages that give your business a strong visual identity.",
    price: "From R2,500",
    features: [
      "Logo Design",
      "Color Palette",
      "Typography",
      "Brand Guidelines",
      "Social Assets",
    ],
  },
  {
    title: "Digital Business Setup",
    description: "Helping businesses establish a strong online presence and operational systems.",
    price: "From R4,000",
    features: [
      "Google Business Setup",
      "Professional Email",
      "Domain Setup",
      "Business Automation",
      "Online Presence Strategy",
    ],
  },
  {
    title: "UI/UX Design",
    description: "Clean and intuitive interfaces designed to improve customer experience.",
    price: "From R2,000",
    features: [
      "Wireframes",
      "Mobile UI",
      "Desktop UI",
      "Interactive Prototypes",
      "Modern Design Systems",
    ],
  },
  {
    title: "Website Maintenance",
    description: "Monthly support and maintenance to keep websites secure and updated.",
    price: "From R500/month",
    features: [
      "Bug Fixes",
      "Security Updates",
      "Performance Optimization",
      "Content Updates",
      "Technical Support",
    ],
  },
  {
    title: "SEO & Optimization",
    description: "Improve visibility on Google and increase traffic through optimization.",
    price: "From R1,500",
    features: [
      "SEO Audit",
      "Keyword Optimization",
      "Performance Improvements",
      "Google Indexing",
      "Analytics Setup",
    ],
  },
  {
    title: "Social Media Design",
    description: "Professional social media visuals for marketing and brand awareness.",
    price: "From R700",
    features: [
      "Instagram Posts",
      "Facebook Banners",
      "Story Designs",
      "Marketing Graphics",
      "Brand Consistency",
    ],
  },
];

export const WRITINGS = [
  {
    title: "The Architecture of Operational Chaos",
    excerpt: "Why most businesses fail to scale not because of product, but because of invisible systems friction.",
    date: "Jun 12, 2024",
    readTime: "6 min read",
    tags: ["Systems", "Scale", "Operations"],
  },
  {
    title: "Meaning in the Machine",
    excerpt: "Exploring the intersection of human fulfillment and the tools we use to manifest progress.",
    date: "May 28, 2024",
    readTime: "8 min read",
    tags: ["Philosophy", "Design", "Tech Culture"],
  },
  {
    title: "Building for 1,000 Days",
    excerpt: "The philosophy of systems longevity and why 'move fast and break things' is dying.",
    date: "May 15, 2024",
    readTime: "5 min read",
    tags: ["Resilience", "Product", "Architecture"],
  },
  {
    title: "When AI Is Not the Answer",
    excerpt: "A practical guide to choosing the right automation path instead of chasing the latest AI trend.",
    date: "Jul 02, 2024",
    readTime: "7 min read",
    tags: ["AI", "Strategy", "Decision Making"],
  },
  {
    title: "Designing Systems for Real Teams",
    excerpt: "How to build workflows, dashboards, and processes that people actually use.",
    date: "Jul 18, 2024",
    readTime: "6 min read",
    tags: ["UX", "Workflow", "Adoption"],
  },
  {
    title: "Research Notes on Cloud Cost Control",
    excerpt: "Simple operational patterns for keeping cloud spend predictable without sacrificing velocity.",
    date: "Aug 05, 2024",
    readTime: "5 min read",
    tags: ["Cloud", "Efficiency", "Research"],
  },
];
